### ISSUE TITLE
Still having issues with cxx frontend linking...

### ISSUE THREAD

**Issue by mattzett** [gemini3d/gemini3d#91] opened 2022-03-08 00:22 UTC
gcc 11.2 on Centos Stream 8:

```
[ 60%] Linking CXX executable ../gemini.bin
/opt/rh/gcc-toolset-11/root/usr/bin/ld: /home/parallels/Projects/gemini_libs/lib/libfilesystem.a(fs.cpp.o): in function `std::vector<std::__cxx11::sub_match<char const*>, std::allocator<std::__cxx11::sub_match<char const*> > >::operator=(std::vector<std::__cxx11::sub_match<char const*>, std::allocator<std::__cxx11::sub_match<char const*> > > const&) [clone .isra.0]':
fs.cpp:(.text+0x488): undefined reference to `operator new(unsigned long)'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: fs.cpp:(.text+0x4ca): undefined reference to `operator delete(void*, unsigned long)'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: fs.cpp:(.text+0x57e): undefined reference to `std::__throw_bad_array_new_length()'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: fs.cpp:(.text+0x583): undefined reference to `std::__throw_bad_alloc()'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: /home/parallels/Projects/gemini_libs/lib/libfilesystem.a(fs.cpp.o): in function `std::vector<std::__cxx11::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::allocator<std::__cxx11::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >::operator=(std::vector<std::__cxx11::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::allocator<std::__cxx11::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > const&) [clone .isra.0]':
fs.cpp:(.text+0x650): undefined reference to `operator new(unsigned long)'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: fs.cpp:(.text+0x692): undefined reference to `operator delete(void*, unsigned long)'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: fs.cpp:(.text+0x74e): undefined reference to `std::__throw_bad_array_new_length()'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: fs.cpp:(.text+0x753): undefined reference to `std::__throw_bad_alloc()'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: /home/parallels/Projects/gemini_libs/lib/libfilesystem.a(fs.cpp.o): in function `std::__cxx11::regex_traits<char>::isctype(char, std::__cxx11::regex_traits<char>::_RegexMask) const [clone .isra.0]':
fs.cpp:(.text+0x843): undefined reference to `std::ctype<char> const& std::use_facet<std::ctype<char> >(std::locale const&)'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: fs.cpp:(.text+0x88c): undefined reference to `std::ctype<char>::_M_widen_init() const'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: /home/parallels/Projects/gemini_libs/lib/libfilesystem.a(fs.cpp.o): in function `void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*>(char const*, char const*, std::forward_iterator_tag) [clone .constprop.0]':
fs.cpp:(.text+0x92b): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: fs.cpp:(.text+0x959): undefined reference to `std::__throw_logic_error(char const*)'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: /home/parallels/Projects/gemini_libs/lib/libfilesystem.a(fs.cpp.o): in function `std::filesystem::__cxx11::path::path<char const*, std::filesystem::__cxx11::path>(char const* const&, std::filesystem::__cxx11::path::format) [clone .constprop.0] [clone .isra.0]':
fs.cpp:(.text+0x997): undefined reference to `std::filesystem::__cxx11::path::_List::_List()'

```

**Comment by mattzett** [comment] 2022-03-08 00:23
Should we just do a plain C version for now?

**Comment by scivision** [comment] 2022-03-08 19:26
The underlying library is C++ so it's not the frontend issue. I.e. it's having problems with external library that is C++.
This is Intel compiler?
Can you try seeing what the command that's failing is with:

```sh
cmake -B build -G Ninja
cmake --build build -t gemini.bin
```

That will print just above those errors the command that is failing.

Also I use gcc-toolset-9.  I haven't tried 11-not sure if that's an issue.

**Comment by scivision** [comment] 2022-03-08 20:23
I just tried and it worked with gcc-toolset-9 and oneAPI  
```
$ ifort --version
ifort (IFORT) 2021.5.0 20211109
$  icx --version
Intel(R) oneAPI DPC++/C++ Compiler 2022.0.0 (2022.0.0.20211123)
```

**Comment by scivision** [comment] 2022-03-08 20:40
OK it appears you were talking about plain GCC. It appears there may be some bug with gcc-toolset-11 as g++ is still version 8.5. The other gcc-toolset-9 and gcc-toolset-10 do work with g++ as intended, so I would try 9 or 10.

**Comment by scivision** [comment] 2022-03-08 20:42
These work:
```sh
scl enable gcc-toolset-10 bash
$ cmake -B build10
-- The C compiler identification is GNU 10.3.1
-- The CXX compiler identification is GNU 10.3.1
-- The Fortran compiler identification is GNU 10.3.1
```

**Comment by scivision** [comment] 2022-03-08 20:44
This also works--I don't get the error you did, despite different compiler versions:

```sh
$ scl enable gcc-toolset-11 bash
$ cmake -B build11
-- The C compiler identification is GNU 11.2.1
-- The CXX compiler identification is GNU 8.5.0
-- The Fortran compiler identification is GNU 11.2.1
...
$ cmake --build build11
...
[392/392] Linking CXX executable gemini.bin
```
All `ctest` passes with it too

**Comment by scivision** [comment] 2022-04-08 18:16
From a little more experience since then, this looks like maybe the wrong libstdc++ was being linked. I'm not sure. However I think it works now, so closing.

**Closed by scivision** 2022-04-08 18:16 UTC
Labels: compiler
